tarot_cards = [
    # Major Arcana
    {"name": "The Fool", "image_url": "/static/images/the_fool.jpg",
     "upright_meaning": "New beginnings, spontaneity, free spirit.",
     "reversed_meaning": "Recklessness, lack of direction, naivety."},
    {"name": "The Magician", "image_url": "/static/images/the_magician.jpg",
     "upright_meaning": "Manifestation, power, resourcefulness.",
     "reversed_meaning": "Manipulation, poor planning, untapped talent."},
    {"name": "The High Priestess", "image_url": "/static/images/the_high_priestess.jpg",
     "upright_meaning": "Intuition, sacred knowledge, divine feminine.",
     "reversed_meaning": "Secrets, disconnected from intuition, withdrawal."},
    {"name": "The Empress", "image_url": "/static/images/the_empress.jpg",
     "upright_meaning": "Femininity, beauty, nature, abundance.",
     "reversed_meaning": "Creative block, dependence on others."},
    {"name": "The Emperor", "image_url": "/static/images/the_emperor.jpg",
     "upright_meaning": "Authority, establishment, structure, father figure.",
     "reversed_meaning": "Domination, excessive control, lack of discipline."},
    {"name": "The Hierophant", "image_url": "/static/images/the_hierophant.jpg",
     "upright_meaning": "Spiritual wisdom, tradition, conformity.",
     "reversed_meaning": "Personal beliefs, freedom, challenging the status quo."},
    {"name": "The Lovers", "image_url": "/static/images/the_lovers.jpg",
     "upright_meaning": "Love, harmony, relationships, choices.",
     "reversed_meaning": "Self-love, imbalance, misalignment of values."},
    {"name": "The Chariot", "image_url": "/static/images/the_chariot.jpg",
     "upright_meaning": "Control, willpower, success, determination.",
     "reversed_meaning": "Self-doubt, lack of direction, aggression."},
    {"name": "Strength", "image_url": "/static/images/strength.jpg",
     "upright_meaning": "Courage, bravery, focus, inner strength.",
     "reversed_meaning": "Weakness, insecurity, lack of self-discipline."},
    {"name": "The Hermit", "image_url": "/static/images/the_hermit.jpg",
     "upright_meaning": "Soul-searching, introspection, being alone.",
     "reversed_meaning": "Isolation, loneliness, withdrawal."},
    {"name": "Wheel of Fortune", "image_url": "/static/images/wheel_of_fortune.jpg",
     "upright_meaning": "Luck, karma, cycles of life, destiny.",
     "reversed_meaning": "Bad luck, resistance to change, lack of control."},
    {"name": "Justice", "image_url": "/static/images/justice.jpg",
     "upright_meaning": "Fairness, truth, accountability, cause and effect.",
     "reversed_meaning": "Injustice, dishonesty, imbalance."},
    {"name": "The Hanged Man", "image_url": "/static/images/the_hanged_man.jpg",
     "upright_meaning": "Letting go, new perspectives, suspension.",
     "reversed_meaning": "Resistance, delays, stagnation."},
    {"name": "Death", "image_url": "/static/images/death.jpg",
     "upright_meaning": "Endings, transformation, rebirth.",
     "reversed_meaning": "Fear of change, personal transformation delayed."},
    {"name": "Temperance", "image_url": "/static/images/temperance.jpg",
     "upright_meaning": "Balance, moderation, patience, harmony.",
     "reversed_meaning": "Imbalance, excess, lack of self-control."},
    {"name": "The Devil", "image_url": "/static/images/the_devil.jpg",
     "upright_meaning": "Addiction, materialism, temptation, bondage.",
     "reversed_meaning": "Breaking free, reclaiming power, overcoming fear."},
    {"name": "The Tower", "image_url": "/static/images/the_tower.jpg",
     "upright_meaning": "Sudden upheaval, chaos, destruction, revelation.",
     "reversed_meaning": "Avoiding disaster, delaying the inevitable."},
    {"name": "The Star", "image_url": "/static/images/the_star.jpg",
     "upright_meaning": "Hope, inspiration, serenity, renewal.",
     "reversed_meaning": "Lack of faith, hopelessness, despair."},
    {"name": "The Moon", "image_url": "/static/images/the_moon.jpg",
     "upright_meaning": "Illusion, intuition, mystery, dreams.",
     "reversed_meaning": "Confusion, deception, fear of the unknown."},
    {"name": "The Sun", "image_url": "/static/images/the_sun.jpg",
     "upright_meaning": "Success, vitality, positivity, abundance.",
     "reversed_meaning": "Lack of clarity, pessimism, temporary success."},
    {"name": "Judgment", "image_url": "/static/images/judgment.jpg",
     "upright_meaning": "Judgment, rebirth, inner calling, self-reflection.",
     "reversed_meaning": "Self-doubt, indecision, unwillingness to change."},
    {"name": "The World", "image_url": "/static/images/the_world.jpg",
     "upright_meaning": "Completion, accomplishment, travel, wholeness.",
     "reversed_meaning": "Incompletion, stagnation, delayed success."},

    # Minor Arcana (Wands, Cups, Swords, Pentacles)
    # Suit of Wands
    {"name": "Ace of Wands", "image_url": "/static/images/ace_of_wands.jpg",
     "upright_meaning": "Inspiration, new opportunities, potential.",
     "reversed_meaning": "Delays, lack of motivation, weighed down."},
    {"name": "Two of Wands", "image_url": "/static/images/two_of_wands.jpg",
     "upright_meaning": "Planning, decisions, discovery.",
     "reversed_meaning": "Fear of change, lack of planning, playing safe."},
    {"name": "Three of Wands", "image_url": "/static/images/three_of_wands.jpg",
     "upright_meaning": "Expansion, foresight, preparation.",
     "reversed_meaning": "Lack of foresight, obstacles, delays."},
    {"name": "Four of Wands", "image_url": "/static/images/four_of_wands.jpg",
     "upright_meaning": "Celebration, harmony, homecoming.",
     "reversed_meaning": "Disruption, lack of celebration, instability."},
    {"name": "Five of Wands", "image_url": "/static/images/five_of_wands.jpg",
     "upright_meaning": "Conflict, competition, struggle.",
     "reversed_meaning": "Avoiding conflict, resolving differences."},
    {"name": "Six of Wands", "image_url": "/static/images/six_of_wands.jpg",
     "upright_meaning": "Victory, recognition, success.",
     "reversed_meaning": "Failure, lack of recognition, lack of self-confidence."},
    {"name": "Seven of Wands", "image_url": "/static/images/seven_of_wands.jpg",
     "upright_meaning": "Perseverance, defense, challenges.",
     "reversed_meaning": "Giving up, lack of persistence, overwhelmed."},
    {"name": "Eight of Wands", "image_url": "/static/images/eight_of_wands.jpg",
     "upright_meaning": "Speed, action, movement.",
     "reversed_meaning": "Delays, lack of progress, standing still."},
    {"name": "Nine of Wands", "image_url": "/static/images/nine_of_wands.jpg",
     "upright_meaning": "Resilience, persistence, guarding what you've built.",
     "reversed_meaning": "Exhaustion, giving up, burnout."},
    {"name": "Ten of Wands", "image_url": "/static/images/ten_of_wands.jpg",
     "upright_meaning": "Burden, responsibility, hard work.",
     "reversed_meaning": "Stress, release of burden, overwhelm."},
    {"name": "Page of Wands", "image_url": "/static/images/page_of_wands.jpg",
     "upright_meaning": "Adventure, enthusiasm, curiosity.",
     "reversed_meaning": "Insecurity, procrastination, lack of direction."},
    {"name": "Knight of Wands", "image_url": "/static/images/knight_of_wands.jpg",
     "upright_meaning": "Action, determination, energy.",
     "reversed_meaning": "Impulsiveness, lack of focus, inconsistency."},
    {"name": "Queen of Wands", "image_url": "/static/images/queen_of_wands.jpg",
     "upright_meaning": "Confidence, creativity, determination.",
     "reversed_meaning": "Jealousy, insecurity, burnout."},
    {"name": "King of Wands", "image_url": "/static/images/king_of_wands.jpg",
     "upright_meaning": "Leadership, vision, entrepreneurship.",
     "reversed_meaning": "Arrogance, lack of direction, selfishness."},
# Suit of Cups (14 Cards)
    {"name": "Four of Cups", "image_url": "/static/images/four_of_cups.jpg",
     "upright_meaning": "Apathy, contemplation, emotional withdrawal.",
     "reversed_meaning": "Boredom, new possibilities, seeking opportunities."},
    {"name": "Five of Cups", "image_url": "/static/images/five_of_cups.jpg",
     "upright_meaning": "Loss, grief, focusing on the negative.",
     "reversed_meaning": "Moving on, accepting the past, healing."},
    {"name": "Six of Cups", "image_url": "/static/images/six_of_cups.jpg",
     "upright_meaning": "Nostalgia, childhood memories, innocence.",
     "reversed_meaning": "Stuck in the past, emotional baggage, immaturity."},
    {"name": "Seven of Cups", "image_url": "/static/images/seven_of_cups.jpg",
     "upright_meaning": "Choices, illusions, opportunities.",
     "reversed_meaning": "Clarity, reality check, focusing on one path."},
    {"name": "Eight of Cups", "image_url": "/static/images/eight_of_cups.jpg",
     "upright_meaning": "Walking away, leaving the past behind, searching for meaning.",
     "reversed_meaning": "Fear of change, stuck in a situation, avoiding growth."},
    {"name": "Nine of Cups", "image_url": "/static/images/nine_of_cups.jpg",
     "upright_meaning": "Contentment, satisfaction, emotional fulfillment.",
     "reversed_meaning": "Unfulfilled desires, emptiness, false satisfaction."},
    {"name": "Ten of Cups", "image_url": "/static/images/ten_of_cups.jpg",
     "upright_meaning": "Happiness, family, emotional harmony, fulfillment.",
     "reversed_meaning": "Disharmony, broken relationships, emotional instability."},
    {"name": "Page of Cups", "image_url": "/static/images/page_of_cups.jpg",
     "upright_meaning": "Creativity, intuition, emotional messages.",
     "reversed_meaning": "Immaturity, emotional instability, blocked creativity."},
    {"name": "Knight of Cups", "image_url": "/static/images/knight_of_cups.jpg",
     "upright_meaning": "Romance, idealism, pursuit of dreams.",
     "reversed_meaning": "Moodiness, unrealistic expectations, disappointment."},
    {"name": "Queen of Cups", "image_url": "/static/images/queen_of_cups.jpg",
     "upright_meaning": "Compassion, nurturing, emotional wisdom.",
     "reversed_meaning": "Emotional instability, overindulgence, mood swings."},
    {"name": "King of Cups", "image_url": "/static/images/king_of_cups.jpg",
     "upright_meaning": "Emotional balance, diplomacy, wisdom, leadership.",
     "reversed_meaning": "Emotional repression, coldness, manipulation."},
# Suit of Swords (14 Cards)
    {"name": "Ace of Swords", "image_url": "/static/images/ace_of_swords.jpg",
     "upright_meaning": "Mental clarity, truth, new ideas, breakthroughs.",
     "reversed_meaning": "Confusion, dishonesty, lack of clarity."},
    {"name": "Two of Swords", "image_url": "/static/images/two_of_swords.jpg",
     "upright_meaning": "Indecision, blocked emotions, difficult choices.",
     "reversed_meaning": "Making decisions, releasing a stalemate."},
    {"name": "Three of Swords", "image_url": "/static/images/three_of_swords.jpg",
     "upright_meaning": "Heartbreak, betrayal, emotional pain.",
     "reversed_meaning": "Healing, moving on, forgiveness."},
    {"name": "Four of Swords", "image_url": "/static/images/four_of_swords.jpg",
     "upright_meaning": "Rest, recovery, meditation, retreat.",
     "reversed_meaning": "Burnout, exhaustion, lack of recovery."},
    {"name": "Five of Swords", "image_url": "/static/images/five_of_swords.jpg",
     "upright_meaning": "Conflict, tension, win-at-all-costs attitude.",
     "reversed_meaning": "Resolution, reconciliation, compromise."},
    {"name": "Six of Swords", "image_url": "/static/images/six_of_swords.jpg",
     "upright_meaning": "Transition, moving forward, change.",
     "reversed_meaning": "Stagnation, inability to move on, troubled waters."},
    {"name": "Seven of Swords", "image_url": "/static/images/seven_of_swords.jpg",
     "upright_meaning": "Deception, secrecy, strategy.",
     "reversed_meaning": "Revealed secrets, coming clean, dishonesty."},
    {"name": "Eight of Swords", "image_url": "/static/images/eight_of_swords.jpg",
     "upright_meaning": "Restriction, feeling trapped, mental anguish.",
     "reversed_meaning": "Liberation, new perspective, overcoming limitations."},
    {"name": "Nine of Swords", "image_url": "/static/images/nine_of_swords.jpg",
     "upright_meaning": "Anxiety, nightmares, fear, worry.",
     "reversed_meaning": "Relief, overcoming fear, insomnia."},
    {"name": "Ten of Swords", "image_url": "/static/images/ten_of_swords.jpg",
     "upright_meaning": "Betrayal, backstabbing, painful endings.",
     "reversed_meaning": "Recovery, rebirth, learning from pain."},
    {"name": "Page of Swords", "image_url": "/static/images/page_of_swords.jpg",
     "upright_meaning": "Curiosity, mental exploration, communication.",
     "reversed_meaning": "Gossip, dishonesty, procrastination."},
    {"name": "Knight of Swords", "image_url": "/static/images/knight_of_swords.jpg",
     "upright_meaning": "Action, drive, quick thinking, ambition.",
     "reversed_meaning": "Impulsiveness, haste, recklessness."},
    {"name": "Queen of Swords", "image_url": "/static/images/queen_of_swords.jpg",
     "upright_meaning": "Perception, wisdom, clarity, independence.",
     "reversed_meaning": "Coldness, bitterness, manipulation."},
    {"name": "King of Swords", "image_url": "/static/images/king_of_swords.jpg",
     "upright_meaning": "Intellect, authority, truth, strategy.",
     "reversed_meaning": "Abuse of power, manipulation, injustice."},
# Suit of Pentacles (14 Cards)
    {"name": "Ace of Pentacles", "image_url": "/static/images/ace_of_pentacles.jpg",
     "upright_meaning": "Prosperity, new beginnings, financial opportunity.",
     "reversed_meaning": "Missed opportunities, lack of resources, financial instability."},
    {"name": "Two of Pentacles", "image_url": "/static/images/two_of_pentacles.jpg",
     "upright_meaning": "Balance, juggling priorities, adaptability.",
     "reversed_meaning": "Overwhelm, imbalance, lack of focus."},
    {"name": "Three of Pentacles", "image_url": "/static/images/three_of_pentacles.jpg",
     "upright_meaning": "Collaboration, teamwork, skill development.",
     "reversed_meaning": "Lack of teamwork, poor craftsmanship, delays."},
    {"name": "Four of Pentacles", "image_url": "/static/images/four_of_pentacles.jpg",
     "upright_meaning": "Security, stability, material possession.",
     "reversed_meaning": "Greed, possessiveness, material loss."},
    {"name": "Five of Pentacles", "image_url": "/static/images/five_of_pentacles.jpg",
     "upright_meaning": "Hardship, financial struggle, exclusion.",
     "reversed_meaning": "Recovery, new opportunities, spiritual growth."},
    {"name": "Six of Pentacles", "image_url": "/static/images/six_of_pentacles.jpg",
     "upright_meaning": "Generosity, charity, giving and receiving.",
     "reversed_meaning": "Inequality, imbalance, selfishness."},
    {"name": "Seven of Pentacles", "image_url": "/static/images/seven_of_pentacles.jpg",
     "upright_meaning": "Patience, hard work, assessing progress.",
     "reversed_meaning": "Impatience, poor investment, lack of reward."},
    {"name": "Eight of Pentacles", "image_url": "/static/images/eight_of_pentacles.jpg",
     "upright_meaning": "Skill development, apprenticeship, diligence.",
     "reversed_meaning": "Lack of focus, poor craftsmanship, disinterest."},
    {"name": "Nine of Pentacles", "image_url": "/static/images/nine_of_pentacles.jpg",
     "upright_meaning": "Wealth, independence, self-sufficiency, luxury.",
     "reversed_meaning": "Financial insecurity, dependence, overspending."},
    {"name": "Ten of Pentacles", "image_url": "/static/images/ten_of_pentacles.jpg",
     "upright_meaning": "Legacy, family, financial success, wealth.",
     "reversed_meaning": "Financial instability, family conflict, loss of inheritance."},
    {"name": "Page of Pentacles", "image_url": "/static/images/page_of_pentacles.jpg",
     "upright_meaning": "New opportunities, manifestation, learning.",
     "reversed_meaning": "Lack of focus, poor planning, financial loss."},
    {"name": "Knight of Pentacles", "image_url": "/static/images/knight_of_pentacles.jpg",
     "upright_meaning": "Hard work, responsibility, commitment.",
     "reversed_meaning": "Stagnation, laziness, lack of progress."},
    {"name": "Queen of Pentacles", "image_url": "/static/images/queen_of_pentacles.jpg",
     "upright_meaning": "Nurturing, practical, grounded, abundance.",
     "reversed_meaning": "Overwhelmed, materialism, neglecting others."},
    {"name": "King of Pentacles", "image_url": "/static/images/king_of_pentacles.jpg",
     "upright_meaning": "Wealth, authority, business success, stability.",
     "reversed_meaning": "Greed, financial mismanagement, lack of security."},
]